apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-myapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-myapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-myapp
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.image }}"
        env:
        - name: DB_HOST
          value: "{{ .Values.db.host }}"
        ports:
        - containerPort: {{ .Values.service.port }}